### ISSUE TITLE
More printers

### ISSUE THREAD

**Issue by roadwan** [msteitz/homebridge-octoprint-connect#3]
I would really like to add more printers to see temps in HomeKit. Is it possible? Thank you

**Comment by msteitz** [comment]
Hi! 

Sorry for the late response. I looked into this topic. Unfortunately Octoprint doesn't support connections to multiple printers simultaneously. Since the plugin establishes a direct connection to a single instance of octoprint, this means that the "one printer" limitation is also effective for the plugin.

However, as described in this article (https://all3dp.com/2/octoprint-multiple-printers/) there are a few workarounds. If you create multiple instances of Octoprint for example, you could create one accessory per instance and get multiple printers into HomeKit through that.

Sorry that there is no easy to use direct solution to your request.

**Comment by roadwan** [comment]
Hello msteitz,

thank you for your reply, I appreciate it. 

The situation is, I have 2 x raspberry pi 3b, each with its own octoprint instances (it means 2x API keys) and 1 another raspberry pi 4/ 4GB where homebridge run..
For each printer there is one raspberry and I wish to add 2 printers with separate credentials. 
I dont know how hard is to add another instance to your plugin but is it good message for you that there is another api? 
I just wish to add another interface for another: 
 - printer name 
 - ip address and 
 - api key
![image](https://user-images.githubusercontent.com/70112346/104125786-56e56100-5359-11eb-9f86-67a45c0db07a.png)

Simply repeat the accessory script.

Is it possible?

        {
            "accessory": "Octoprint-Temp",
            "name": "MK3s",
            "server": "http://xx.x.x.xx",
            "api_key": "********** ********** ********** **"
        }
        {
            "accessory": "Octoprint-Temp",
            "name": "Mini",
            "server": "http://xx.x.x.xx",
            "api_key": "********** ********** ********** **"
        }

Thank you and have a nice new year start,
Roadwan

**Comment by msteitz** [comment]
Ok, thanks for clarification! I have a few ideas how this could work and will test it with the plugin. 

It will take a few days before I can post the results since my free time is limited due to work right now. Sorry for that.

**Comment by msteitz** [comment]
Ok, sometimes I just have to do things :) I created and uploaded version 1.1.3 which gives you the ability to add multiple accessories through the interface (button on the bottom left). Tested it with two octoprint instances on two different machines and it seem to work. However, I only have one printer, so there is still a chance that it fails in a real multi printer setup.

Please update and test. Happy to hear about your results!

**Comment by roadwan** [comment]
Thats fantastic! 👍 :D

Working like charm! :)

![Uploading image.png…]()

Thanks a lot! :)

**Comment by roadwan** [comment]
Thats fantastic! 👍 :D

Working like charm! :)

![Výstřižek](https://user-images.githubusercontent.com/70112346/104284555-7e9c0c80-54b2-11eb-8117-ca0bac4cac7d.JPG)

Thanks a lot! :)

**Comment by msteitz** [comment]
Happy to help :)
